### ISSUE TITLE
Error: "Text index consists of several parts! We cannot handle this yet"

### ISSUE THREAD

**Issue by hj-99** [medvedevgroup/eskemap#4]
Hi Author,

I executed the following command:

./eskemap -p ./data/reads.fasta -s ./data/ref.fasta -k 9 -w 10 -b ./highAbundKmersMiniK15w10Lrgr100BtStrnds.txt -r 0.1 -c 1 -u 1 -t 0.9
However, I encountered the following error message:

ERROR: Text index consists of several parts! We cannot handle this yet

I am unsure about the cause of this error and would greatly appreciate your guidance on how to resolve it. If you need any additional information or details about my setup, please let me know.

Thank you in advance for your time and assistance.

**Comment by tischulz1** [comment]
Hi @hj-99,

I guess the problem here is that your reference sequence file (./data/ref.fasta) is too large. ESKEMAP relies on the code of [minimap2](https://github.com/lh3/minimap2) to construct an index of the given input files. As soon as an input sequence file becomes too large ($\geq 4$ billion base pairs by default), minimap2 starts to load and index the sequences in chunks. Afterwards, such an index also must be read in chunks which is currently not supported by ESKEMAP.

There are two possibilities how to solve this problem quickly:

1. If your reference sequence file does not contain any sequence longer than 4 billion base pairs, you could distribute the sequences on multiple files. Just make sure that none of your files contains more than 4 billion base pairs in total. Afterwards, you can run ESKEMAP on each file separately. As the tool processes reference sequences independently your results should not change.

2. If you tell me how many base pairs your reference sequence file contains in total, I can change the default file size limit of minimap2 in the code. This should prevent minimap2 from reading the reference sequence file in chunks when constructing the index and avoid the error.

Please let me know if either Solution 1 worked for you or how many base pairs are contained in ./data/ref.fasta.

**Comment by tischulz1** [comment]
I assume this issue has been solved. Please feel free to reopen it otherwise.
